on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.22.2'
    - run: go test -cover ./...
